### ISSUE TITLE
Can't cache/pickle aldjemy objects

### ISSUE THREAD

**Issue by erikcw** [aldjemy/aldjemy#12]
When attempting to cache an aldjemy object, Django/tastypie throws the following traceback:

```
Traceback (most recent call last): 
  File "/app/.heroku/python/lib/python2.7/site-packages/tastypie/resources.py", line 202, in wrapper 
    response = callback(request, *args, **kwargs) 
  File "/app/.heroku/python/lib/python2.7/site-packages/tastypie/resources.py", line 449, in dispatch_detail 
    return self.dispatch('detail', request, **kwargs) 
  File "/app/api/resources.py", line 54, in dispatch 
    return super(BasePortalResource, self).dispatch(request_type, request, **kwargs) 
  File "/app/.heroku/python/lib/python2.7/site-packages/tastypie/resources.py", line 472, in dispatch 
    response = method(request, **kwargs) 
  File "/app/.heroku/python/lib/python2.7/site-packages/tastypie/resources.py", line 1303, in get_detail 
    obj = self.cached_obj_get(bundle=basic_bundle, **self.remove_api_resource_names(kwargs)) 
  File "/app/.heroku/python/lib/python2.7/site-packages/tastypie/resources.py", line 1122, in cached_obj_get 
    self._meta.cache.set(cache_key, cached_bundle) 
  File "/app/.heroku/python/lib/python2.7/site-packages/tastypie/cache.py", line 81, in set 
    cache.set(key, value, timeout) 
  File "/app/.heroku/python/lib/python2.7/site-packages/django_pylibmc/memcached.py", line 106, in set 
    MIN_COMPRESS) 
  File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-1.11.0.55/newrelic/api/memcache_trace.py", line 73, in __call__ 
    return self._nr_next_object(*args, **kwargs) 
PicklingError: Can't pickle <class 'aldjemy.orm.Campaign'>: attribute lookup aldjemy.orm.Campaign failed
```

Django 1.5.1
Tastypie 0.9.14
Aldjemy 0.3.8

**Comment by ryanhiebert** [comment]
I'm not totally opposed to making the instances pickle-able, but I really don't care about it. If someone wants it, they'd need to propose a plan to work it in. I don't feel like it makes a whole lot of sense to worry about it.
