### ISSUE TITLE
Use db_column in ForeignKey field

### ISSUE THREAD

**Issue by catgatp** [aldjemy/aldjemy#264]
I have the following model:
```
from django.db import models

class Item(models.Model):
    label = models.TextField(null=False, blank=False)
    legacy_id = models.CharField(max_length=255, unique=True, null=False, blank=False)
class RelatedToItemViaUniqueField(models.Model):
    item = models.ForeignKey(Item,   db_column="item", to_field="legacy_id", on_delete=models.CASCADE
```
run  >python manage.py makemigrations sample
with the following error:
```
(venv) E:\work\python\sqlalchemy\test_project>python manage.py makemigrations sample
Traceback (most recent call last):
  File "manage.py", line 35, in <module>
    execute_from_command_line(sys.argv)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\aldjemy\apps.py", line 13, in ready
    for model, sa_model in construct_models(MetaData()).items():
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\aldjemy\orm.py", line 164, in construct_models
    mapper_registry.map_imperatively(sa_model, local_table=table, properties=attrs)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\decl_api.py", line 999, in map_imperatively
    return _mapper(self, class_, local_table, kw)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\decl_base.py", line 130, in _mapper
    _ImperativeMapperConfig(registry, cls, table, mapper_kw)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\decl_base.py", line 243, in __init__
    self._early_mapping(mapper_kw)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\decl_base.py", line 215, in _early_mapping
    self.map(mapper_kw)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\decl_base.py", line 250, in map
    mapper_cls(self.cls, self.local_table, **mapper_kw),
  File "<string>", line 2, in __init__
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\util\deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 663, in __init__
    self._configure_properties()
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1464, in _configure_properties
    column_key, column, init=False, setparent=True
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1699, in _configure_property
    prop = self._property_from_column(key, prop)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1891, in _property_from_column
    "columns get mapped." % (key, self, column.key, prop)
sqlalchemy.exc.ArgumentError: WARNING: when configuring property 'item' on mapped class RelatedToItemViaUniqueField.sa->sample_relatedtoitemviauniquefield, column 'item' conflicts with property '<Relationsh
ipProperty at 0x19b9e890848; item>'. To resolve this, map the column to the class under a different name in the 'properties' dictionary.  Or, to remove all awareness of the column entirely (including its av
ailability as a foreign key), use the 'include_properties' or 'exclude_properties' mapper arguments to control specifically which table columns get mapped.

```

**Comment by catgatp** [comment]
> Can you reproduce it with a test ? that would help understanding this issue.

db_column and foreign key field duplicate name problem reappears

**Comment by catgatp** [comment]
> Can you reproduce it with a test ? that would help understanding this issue.
model:
```
from django.db import models

class Item(models.Model):
    label = models.TextField(null=False, blank=False)
    legacy_id = models.CharField(max_length=255, unique=True, null=False, blank=False)
class RelatedToItemViaUniqueField(models.Model):
    item = models.ForeignKey(Item,   db_column="item", to_field="legacy_id", on_delete=models.CASCADE)
```
test
```
class FieldTests(TestCase):
    def test_db_column(self):
        Item.objects.create(label="test", legacy_id="1")
        RelatedToItemViaUniqueField.objects.create(item_id="1")
        t = RelatedToItemViaUniqueField.sa.query().one()
        self.assertEqual(t.item.label, "test")
```
run  test
```
E:\work\python\sqlalchemy\test_project\venv\Scripts\python.exe "D:\Program Files\JetBrains\PyCharm 2020.3.3\plugins\python\helpers\pycharm\django_test_manage.py" test sample.tests.FieldTests.test_db_column E:\work\python\sqlalchemy\test_project
Testing started at 17:04 ...
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm 2020.3.3\plugins\python\helpers\pycharm\django_test_manage.py", line 56, in <module>
    django.setup()
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\aldjemy\apps.py", line 13, in ready
    for model, sa_model in construct_models(MetaData()).items():
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\aldjemy\orm.py", line 164, in construct_models
    mapper_registry.map_imperatively(sa_model, local_table=table, properties=attrs)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\decl_api.py", line 999, in map_imperatively
    return _mapper(self, class_, local_table, kw)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\decl_base.py", line 130, in _mapper
    _ImperativeMapperConfig(registry, cls, table, mapper_kw)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\decl_base.py", line 243, in __init__
    self._early_mapping(mapper_kw)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\decl_base.py", line 215, in _early_mapping
    self.map(mapper_kw)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\decl_base.py", line 250, in map
    mapper_cls(self.cls, self.local_table, **mapper_kw),
  File "<string>", line 2, in __init__
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\util\deprecations.py", line 309, in warned
    return fn(*args, **kwargs)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 663, in __init__
    self._configure_properties()
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1464, in _configure_properties
    column_key, column, init=False, setparent=True
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1699, in _configure_property
    prop = self._property_from_column(key, prop)
  File "E:\work\python\sqlalchemy\test_project\venv\lib\site-packages\sqlalchemy\orm\mapper.py", line 1891, in _property_from_column
    "columns get mapped." % (key, self, column.key, prop)
sqlalchemy.exc.ArgumentError: WARNING: when configuring property 'item' on mapped class RelatedToItemViaUniqueField.sa->sample_relatedtoitemviauniquefield, column 'item' conflicts with property '<RelationshipProperty at 0x2483ff5ec48; item>'. To resolve this, map the column to the class under a different name in the 'properties' dictionary.  Or, to remove all awareness of the column entirely (including its availability as a foreign key), use the 'include_properties' or 'exclude_properties' mapper arguments to control specifically which table columns get mapped.
```

**Comment by catgatp** [comment]
> I'm pretty sure there is a `NameError` in the snippet you provided. Please make the effort to make a pull request for the aldjemy test suite.

I have made a pull request

**Comment by ticosax** [comment]
I explained in the pull request https://github.com/aldjemy/aldjemy/pull/266 the reasons why I'm closing it.
