### ISSUE TITLE
Connection closed exception

### ISSUE THREAD

**Issue by erikcw** [aldjemy/aldjemy#32]
``` python

Traceback (most recent call last):
  File "/Users/erik/Dropbox/home/git/proj/api/tests/test_user.py", line 211, in test_post_list_bgt_validation
    resp = self.api_client.post(self.list_url, format='json', data=self.post_data, HTTP_AUTHORIZATION=self.get_credentials())
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/rest_framework/test.py", line 90, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/rest_framework/compat.py", line 150, in generic
    return self.request(**r)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/rest_framework/test.py", line 157, in request
    return super(APIClient, self).request(**kwargs)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/rest_framework/test.py", line 109, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/django/test/client.py", line 440, in request
    six.reraise(*exc_info)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/rest_framework/viewsets.py", line 79, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/rest_framework/views.py", line 403, in dispatch
    response = self.handle_exception(exc)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/rest_framework/views.py", line 400, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/rest_framework/mixins.py", line 52, in create
    if serializer.is_valid():
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/rest_framework/serializers.py", line 550, in is_valid
    return not self.errors
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/rest_framework/serializers.py", line 542, in errors
    ret = self.from_native(data, files)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/rest_framework/serializers.py", line 1021, in from_native
    instance = super(ModelSerializer, self).from_native(data, files)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/rest_framework/serializers.py", line 370, in from_native
    attrs = self.perform_validation(attrs)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/rest_framework/serializers.py", line 303, in perform_validation
    attrs = validate_method(attrs, source)
  File "/Users/erik/Dropbox/home/git/proj/api/serializers.py", line 267, in validate_bgt
    portal.validators.validate_user_bgt(bgt, margin, attrs['user'], self.object)
  File "/Users/erik/Dropbox/home/git/proj/portal/validators.py", line 35, in validate_user_bgt
    net_expsr = LedgerAccount.objects.calculate_user_net_expsr(user, instance_pk_list, adjusted_new_bgt or decimal.Decimal('0'))
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/erik/Dropbox/home/git/proj/portal/managers.py", line 997, in calculate_user_net_expsr
    gross_expsr = gross_expsr.scalar() or decimal.Decimal(0)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2429, in scalar
    ret = self.one()
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2398, in one
    ret = list(self)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2441, in __iter__
    return self._execute_and_instances(context)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2456, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 841, in execute
    return meth(self, multiparams, params)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 938, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1005, in _execute_context
    None, None)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1271, in _handle_dbapi_exception
    exc_info
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1001, in _execute_context
    context = constructor(dialect, self, conn, *args)
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 561, in _init_compiled
    self.cursor = self.create_cursor()
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 442, in create_cursor
    return self._dbapi_connection.cursor()
  File "/Users/erik/.virtualenvs/proj/lib/python2.7/site-packages/sqlalchemy/pool.py", line 770, in cursor
    return self.connection.cursor(*args, **kwargs)
  File "/Users/erik/Dropbox/home/git/aldjemy/aldjemy/wrapper.py", line 23, in __call__
    self.obj = self.obj(*a, **kw)
InterfaceError: (InterfaceError) connection already closed u'SELECT sum(portal_user.bgt - portal_user.bgt * (portal_user.margin / %(margin_1)s)) AS sum_1 \nFROM portal_user \nWHERE portal_user.status = %(status_1)s AND portal_user.user_id = %(user_id_1)s' [immutabledict({})]

----------------------------------------------------------------------
Ran 17 tests in 13.537s

FAILED (errors=1)

```

Django 1.7.8
aldjemy 0.4.1
sqlalchemy 0.9.9 (also tested 1.0.0 and 1.0.6).
psycopg2 2.6.1
Postgres 9.4

**Comment by erikcw** [comment]
I've got a workaround for my test suite for the time being:

```python
class ProjectBaseTestCase(TestCase):
    def tearDown(self):
        session = aljdemy.orm.get_session(alias='default')
        session.close_all()
```

This gets my tests running again, but obviously this is just a bandaid.  This should be fixed at the aldjemy level.

**Comment by ojomio** [comment]
Well, after "monte-carlo" debugging what I found was:
Reference: `sqlalchemy.orm.__init__.create_session()`
>The defaults of create_session() are the opposite of that of
>:func:`sessionmaker`; ``autoflush`` and ``expire_on_commit`` are
>False, ``autocommit`` is True.  In this sense the session acts
>more like the "classic" SQLAlchemy 0.3 session with these.

Then I used session like this:

```python
def get_sa_session():
    session = aldjemy.orm.get_session()
    session.autocommit = False
    session.expire_on_commit = True
    return session
```

When ```autocommit``` is disabled, it seems to work.

if we use session from ```create_session()```, which is what aldjemy does, somehow dbapi (psycopg2 in my case) connection gets closed after successfull retrieval. 
I mean, in my application **every second** query runs fine, and the other half get "Connection already closed"

I put an event listener on ```checkin```(returned to pool) event as well as for ```invalidate``` - that's what it prints out:
```
Connection invalidate <connection object at 0x7fad78acfae8; dsn: 'dbname=fm_test user=psql_admin password=xxxxxxxxxx host=localhost', closed: 1> <sqlalchemy.pool._ConnectionRecord object at 0x7f8208034588> connection already closed
Connection checkin None <sqlalchemy.pool._ConnectionRecord object at 0x7f8208034588>
```
Where ```None``` is dbapi connection and the other obviously is a SQLA _ConnectionRecord wrapper around it

**Comment by ojomio** [comment]
Unfortunately, I was wrong about having bypassed it with `autocommit=False`. This error still occurs unpredictably

**Comment by vadim-pavlov** [comment]
It happens because django closes all DatabaseWrapper instances at the end of the http request, leaving sqlalchemy Session with closed database connection for all subsequent requests:

django/db/__init__.py:
```python
def close_connection(**kwargs):
    for conn in connections.all():
        conn.close()
signals.request_finished.connect(close_connection)
```

So far I've found two possible solutions to this problem:

1. Setup a similar signal handler to reset all sqlalchemy sessions at the end of the request:

    ```python
    from django.core import signals as core_signals

    def close_connection(**kwargs):
        for conn in connections.all():
            if hasattr(conn, 'sa_session'):
                conn.sa_session.close_all()

    core_signals.request_finished.connect(close_connection)
    ```

2. Change  ```_ConnectionRecord.connection``` method to return an instance which knows how to re-establish previously closed connection on ```cursor()``` call:

    ```python
    @property
    def connection(self):
        connection = connections[self.alias]
        if connection.vendor == 'sqlite':
            return SqliteWrapper(connection)
        if self.wrap:
            return Wrapper(connection)
        return connection
    ```

The second approach may also require to extend Wrapper classes to provide sqlalchemy with access to all public attributes of the internal ```DatabaseWrapper.connection``` instance.

**Comment by erikcw** [comment]
So this problem had all but went away with the tweak to the TestCase I mentioned above.

However, after upgrading to Django 1.9.6 (from 1.7) and aldjemy 0.6, these errors started coming back -- and this time in production.

I implemented vadim-pavlov's `request_finished` hook and that seems to have cleaned things right up!

**Comment by AmirMeirbekov** [comment]
I also implemented Vadim's first option with `request_finished` hook. However, I started receiving exceptions about dictionary changed size during iteration:

```
Exception happened during processing of request from ('172.17.0.1', 52223)
Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 138, in run
    self.finish_response()
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 183, in finish_response
    self.close()
  File "/usr/lib/python3.4/wsgiref/simple_server.py", line 38, in close
    SimpleHandler.close(self)
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 321, in close
    self.result.close()
  File "/usr/local/lib/python3.4/dist-packages/django/http/response.py", line 252, in close
    signals.request_finished.send(sender=self._handler_class)
  File "/usr/local/lib/python3.4/dist-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/www/web-services/web_services/urls.py", line 37, in close_connection
    conn.sa_session.close_all()
  File "/usr/local/lib/python3.4/dist-packages/sqlalchemy/orm/session.py", line 56, in close_all
    for sess in _sessions.values():
  File "/usr/lib/python3.4/weakref.py", line 216, in values
    for wr in self.data.values():
RuntimeError: dictionary changed size during iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 141, in run
    self.handle_error()
  File "/usr/local/lib/python3.4/dist-packages/django/core/servers/basehttp.py", line 92, in handle_error
    super(ServerHandler, self).handle_error()
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 368, in handle_error
    self.finish_response()
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 180, in finish_response
    self.write(data)
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 274, in write
    self.send_headers()
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 331, in send_headers
    if not self.origin_server or self.client_is_modern():
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 344, in client_is_modern
    return self.environ['SERVER_PROTOCOL'].upper() != 'HTTP/0.9'
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/socketserver.py", line 613, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.4/dist-packages/django/core/servers/basehttp.py", line 99, in __init__
    super(WSGIRequestHandler, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.4/socketserver.py", line 669, in __init__
    self.handle()
  File "/usr/local/lib/python3.4/dist-packages/django/core/servers/basehttp.py", line 179, in handle
    handler.run(self.server.get_app())
  File "/usr/lib/python3.4/wsgiref/handlers.py", line 144, in run
    self.close()
  File "/usr/lib/python3.4/wsgiref/simple_server.py", line 35, in close
    self.status.split(' ',1)[0], self.bytes_sent
AttributeError: 'NoneType' object has no attribute 'split'
```

So, it appeared that `conn.sa_session.close_all()` to `conn.sa_session.close()` fixes this.

**Comment by akheron** [comment]
I'm also having this issue in production. Django 1.9, Postgres 9.4, aldjemy 0.6. Workaround 1 by @vadim-pavlov (but using `conn.sa_session.close()` instead of `close_all()`) seems to work.

Would setting `CONN_MAX_AGE` in the database settings have any effect on this?

**Comment by akheron** [comment]
I'm also puzzled about why this doesn't happen in development or tests.

**Comment by AmirMeirbekov** [comment]
@akheron As far as I remember, I also had this problem in production. I added `django.core.signals` for closing connections upon request finished. Here is the code I have in the end of `url.py`:

`from django.core import signals as core_signals

def close_connection(**kwargs):
    for conn in connections.all():
        if hasattr(conn, 'sa_session'):
            conn.sa_session.close()

core_signals.request_finished.connect(close_connection)`

**Comment by scythargon** [comment]
@AmirMeirbekov buy why put in `urls.py`? o_O

**Comment by AmirMeirbekov** [comment]
@scythargon the idea is to register your signals when Django web app starts. So, you can put it also in project `__init__.py` or in some app's `models.py`, anywhere, which is loaded on start

**Comment by akheron** [comment]
FWIW, I still have this problem in production, this time with a new project. It only happens when running in uWSGI, and doesn't happen in `./manage.py runserver`. 

The [workaround](https://github.com/Deepwalker/aldjemy/issues/32#issuecomment-245908542) by @AmirMeirbekov fixed it this time, too.

I had forgotten about the problem completely, and was surprised to find my own comment in this issue when investigating for the new project :)

Could the workaround be documented somewhere, e.g. README? Or better still, could this be fixed? It seems to me that @vadim-pavlov has a fix.

**Comment by Deepwalker** [comment]
Can anyone provide PR? Desirable with proper test. It will be amazing if someone can.

**Comment by ryanhiebert** [comment]
I haven't had this issue in my own use-cases, so I'm not confident in writing a test case. Would someone be willing to write up a test case and a PR? I'd love to get this merged into the project.

**Comment by ryanhiebert** [comment]
I'd really like to see this fixed, but this isn't how I'm currently using SQLAlchemy. Would anyone be willing to chat with me or video call to help me reproduce this issue? @erikcw @ojomio @vadim-pavlov @AmirMeirbekov @akheron @scythargon

**Comment by ryanhiebert** [comment]
This is a problem I'd love to see solved, but which I won't personally be taking on in the foreseeable future, and which I'm not sure how to reproduce. If someone else cares enough about it to schedule a time to work on it with me or to assist in reproducing the issue reliably, I'm happy to put in some work to help somebody make a patch, or possibly make it myself at that point. Until then, I'm going to unpin this issue, so that it can be closed as stale.
