### ISSUE TITLE
Django TimeField gives 'datetime.time' object has no attribute 'microseconds' when querying its model's 'sa' attribute

### ISSUE THREAD

**Issue by tackler** [aldjemy/aldjemy#43]
Steps to reproduce
1. Python 2.7.6, pip==9.0.1, Django==1.10.5, MySQL-python==1.2.5, aldjemy==0.6.0
1. Create a model with TimeField
1. Do necessary migrations
1. Create an object of the models using django's "objects.create()". You can give either a string or a datetime.time or datetime.datetime instance for the field.
1. Create a session using `aldjemy.core.get_engine()`
1. `session.query(<model name>.sa).all()` or `<model name>.sa.query().all()` gives the error

```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "~/.virtualenvs/test/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2638, in all
    return list(self)
  File "~/.virtualenvs/test/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 90, in instances
    util.raise_from_cause(err)
  File "~/.virtualenvs/test/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "~/.virtualenvs/test/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 75, in instances
    rows = [proc(row) for row in fetch]
  File "~/.virtualenvs/test/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 437, in _instance
    loaded_instance, populate_existing, populators)
  File "~/.virtualenvs/test/local/lib/python2.7/site-packages/sqlalchemy/orm/loading.py", line 498, in _populate_full
    dict_[key] = getter(row)
  File "~/.virtualenvs/test/local/lib/python2.7/site-packages/sqlalchemy/dialects/mysql/types.py", line 413, in process
    microseconds = value.microseconds
AttributeError: 'datetime.time' object has no attribute 'microseconds'
```

**Comment by tackler** [comment]
This is possibly because Django converts the MySQLdb given datetime.timedelta to datetime.time which is then given to SQLA but it was expecting datetime.timedelta.

**Comment by ryanhiebert** [comment]
Wow, that's quite interesting behavior. @tackler, do you have a suggestion on how we could address this, or is it best to leave it to user code? I tend to feel that making either Django or SQLAlchemy work differently than they were designed is unwise.
