### ISSUE TITLE
Mapper error when db_column == attname on a Model subclass

### ISSUE THREAD

**Issue by cochiseruhulessin** [aldjemy/aldjemy#76]
```
sqlalchemy.exc.ArgumentError: WARNING: when configuring property 'subject' on mapped
class User->usersubjects, column 'subject' conflicts with property '<RelationshipProperty at 0x104453c48; subject>'.
To resolve this, map the column to the class under a different name in the 'properties' dictionary.
Or, to remove all awareness of the column entirely (including its availability as a foreign key),
use the 'include_properties' or 'exclude_properties' mapper arguments to control specifically
which table columns get mapped.
```

This was on a model (`User`) where the parent link field to the parent model `Subject` was declared as an attribute `subject` and instantiated with the argument `db_column='subject'`. Source example will follow.

**Comment by Deepwalker** [comment]
Hey! Example should help.

**Comment by ryanhiebert** [comment]
If anyone has an example of this, please post one, so that I have a test case that can be fixed.

**Comment by matuqam** [comment]
Traceback (most recent call last):
  File "/private/tmp/pys/automap/automap.py", line 25, in <module>
    main()
  File "/private/tmp/pys/automap/automap.py", line 19, in main
    Base.prepare(engine, reflect=True)
  File "/private/tmp/pys/automap/venv/lib/python3.8/site-packages/sqlalchemy/ext/automap.py", line 848, in prepare
    map_config.map()
  File "/private/tmp/pys/automap/venv/lib/python3.8/site-packages/sqlalchemy/ext/declarative/base.py", line 765, in map
    return super(_DeferredMapperConfig, self).map()
  File "/private/tmp/pys/automap/venv/lib/python3.8/site-packages/sqlalchemy/ext/declarative/base.py", line 695, in map
    self.cls.__mapper__ = mp_ = mapper_cls(
  File "<string>", line 2, in mapper
  File "<string>", line 2, in __init__
  File "/private/tmp/pys/automap/venv/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 139, in warned
    return fn(*args, **kwargs)
  File "/private/tmp/pys/automap/venv/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 721, in __init__
    self._configure_properties()
  File "/private/tmp/pys/automap/venv/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 1520, in _configure_properties
    self._configure_property(
  File "/private/tmp/pys/automap/venv/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 1759, in _configure_property
    prop = self._property_from_column(key, prop)
  File "/private/tmp/pys/automap/venv/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 1940, in _property_from_column
    raise sa_exc.ArgumentError(
sqlalchemy.exc.ArgumentError: WARNING: when configuring property 'product_uom' on mapped class stock_move->stock_move, column 'product_uom' conflicts with property '<RelationshipProperty at 0x10d5f77c0; product_uom>'. To resolve this, map the column to the class under a different name in the 'properties' dictionary.  Or, to remove all awareness of the column entirely (including its availability as a foreign key), use the 'include_properties' or 'exclude_properties' mapper arguments to control specifically which table columns get mapped.

**Comment by ryanhiebert** [comment]
Thanks, although I'm not sure this really helps me much. Can you give me steps or a repository to reproduce the issue?
